### ISSUE TITLE
command prompt output unreadable

### ISSUE THREAD

**Issue by cnopt** [Bornhall/gt7telemetry#2]
hello , i'm trying to get the output readable, but all i'm getting is this when running:
 `python3 gt7telemetry.py <ip>`:

  
![image](https://user-images.githubusercontent.com/33091527/218579432-75c5252a-a76b-4d7b-b48d-d50a6239603d.png)

millions of bits of data, never ending

salsa20 has been installed

output is the same even when lines 10-29 are commented out

**Comment by Bornhall** [comment]
Looks to me that your command shell doesn't support ANSI control codes? What are you using?

**Comment by cnopt** [comment]
> Looks to me that your command shell doesn't support ANSI control codes? What are you using?

yep you're right , using Commander or Terminal Preview the output is as expected - standard Command Prompt is what i was using 

thanks for the fast reply
