### ISSUE TITLE
Is there a way to get sector times?

### ISSUE THREAD

**Issue by derSoerrn95** [Bornhall/gt7telemetry#4]
Hi, really nice work - great tool.

I would like to save sector times. Is it possible to get the track specific sectors? Or can I even get the calculated sector times?

**Comment by Bornhall** [comment]
> Hi, really nice work - great tool.
> 
> I would like to save sector times. Is it possible to get the track specific sectors? Or can I even get the calculated sector times?

Unfortunately not, there is nothing about sector times in the telemetry. You'd have to "roll your own" sectors, so to speak, if you want to have anything like that. Not impossible, but it's a lot of work gathering the data from the telemetry and turning it into something usable. Basically, you could capture a lap and use coordinates at regular intervals to put up kind of a "gating system" that could be used as sectors. It wouldn't be the same as the in-game sectors though (or at least not the "same" sector times – even though you could possible get close enough).

**Comment by derSoerrn95** [comment]
Thanks for your fast response! Yeah I thought so... Then I guess I'll build something like you suggested.
